# Generated by Django 5.2 on 2025-04-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Aerolínea',
                'verbose_name_plural': 'Aerolíneas',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID del Tramo')),
                ('departure_time', models.DateTimeField(verbose_name='Hora de Salida')),
                ('arrival_time', models.DateTimeField(verbose_name='Hora de Llegada')),
                ('stops', models.IntegerField(verbose_name='Escalas')),
                ('duration_mins', models.IntegerField(verbose_name='Duración (minutos)')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights_manager.carrier', verbose_name='Aerolínea')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights_manager.place', verbose_name='Aeropuerto de Llegada')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights_manager.place', verbose_name='Aeropuerto de Salida')),
            ],
            options={
                'verbose_name': 'Tramo de Vuelo',
                'verbose_name_plural': 'Tramos de Vuelo',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID del Itinerario')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('agent', models.CharField(max_length=255, verbose_name='Agente')),
                ('agent_rating', models.FloatField(blank=True, null=True, verbose_name='Calificación de la agencia')),
                ('legs', models.ManyToManyField(related_name='itineraries', to='flights_manager.leg', verbose_name='Tramos')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
            },
        ),
    ]
